### ISSUE TITLE
Confusion about repo paths for `hyper-trust-dns`

### ISSUE THREAD

**Issue by Ocramius** [Gelbpunkt/hyper-trust-dns#12]
Hey there,

This is just a question about code location / redirects. I used `hyper-trust-dns` in order to experiment with how small I could go with a `scratch` container in https://github.com/Ocramius/oci-srm-server-mock-rust/blob/75b688929ed338f677a31c0f811b133b9f986a89/Cargo.toml#L26

When browsing from https://docs.rs/hyper-trust-dns/latest/hyper_trust_dns/, I get redirected to this repository.

What happened? Is the original source gone? Should I migrate my implementation?

Thanks in advance!

**Comment by Gelbpunkt** [comment]
The trust-dns project rebranded to hickory-dns, so I renamed this crate accordingly.

**Comment by Ocramius** [comment]
Thanks for clarifying
